# Generated by Django 6.1.2 on 2026-10-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='location_source',
            field=models.CharField(choices=[('site', 'matched to the fuel station on OpenStreetMap'), ('exit', "the stop's highway exit on OpenStreetMap"), ('city', 'centre of its city (no better match)')], default='city', max_length=4),
        ),
    ]
