# Generated by Django 6.1.2 on 2026-10-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanner', '0002_station_location_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='location_source',
            field=models.CharField(choices=[('site', 'matched to its fuel station (OpenStreetMap or Overture Maps)'), ('uncertain', 'matched to a fuel station, but the two sources disagree on which one'), ('exit', "the stop's highway exit on OpenStreetMap"), ('city', 'centre of its city (no better match)')], default='city', max_length=10),
        ),
    ]
